---
- name: Install Nginx
  hosts: webservers
  become: true
  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present
      when: inventory_hostname in ['192.168.80.186', '192.168.80.196', '192.168.80.195']
