- hosts: all
  become: yes

  tasks:
    - import_tasks: roles/common/tasks/main.yml
    - import_tasks: roles/webserver/tasks/main.yml
    - import_tasks: roles/database/tasks/main.yml
    - import_tasks: roles/app/tasks/main.yml
