---
- name: Deploy Web Application with Nginx on Frontend
  hosts: all  # Thay đổi thành 'all' để Ansible có thể tìm kiếm tất cả các máy chủ trong file /etc/ansible/hosts
  vars:
    port: 8080

  tasks:
    - name: Install Nginx on webservers
      apt:
        name: nginx
        state: present
      when: "'{{ inventory_hostname }}' in groups['webservers']"

    - name: Create directory for web content
      file:
        path: "/var/www/html"
        state: directory

    - name: Copy Nginx configuration file
      template:
        src: "nginx.conf.j2"
        dest: "/etc/nginx/sites-available/web"
      notify: "Restart Nginx services"

    - name: Copy registration form HTML file
      copy:
        src: "registration_form.html"
        dest: "/var/www/html/registration_form.html"

    - name: Create webpage
      copy:
        content: "SETA International VN"
        dest: "/var/www/html/index.html"

    - name: Start Nginx service
      service:
        name: nginx
        state: started

  handlers:
    - name: Restart Nginx service
      service:
        name: nginx
        state: restarted
