---
- name: Deploy Web Application with Nginx on Frontend
  hosts: all
  vars:
    port: 8080
    domain_name: "test3.seta-international.vn"

  tasks:
    - name: Install Nginx on webservers
      apt:
        name: nginx
        state: present
      when: "'{{ inventory_hostname }}' in groups['webservers']"

    - name: Create directory for web content
      file:
        path: "/var/www/html"
        state: directory
      when: "'{{ inventory_hostname }}' in groups['webservers']"

    - name: Copy Nginx configuration file
      template:
        src: "nginx.conf.j2"
        dest: "/etc/nginx/sites-enabled/web"
      notify: "Restart Nginx service"
      when: "'{{ inventory_hostname }}' in groups['webservers']"

    - name: Copy registration form HTML file
      copy:
        src: "registration_form.html"
        dest: "/var/www/html/registration_form.html"
      when: "'{{ inventory_hostname }}' in groups['webservers']"

    - name: Create webpage
      copy:
        content: "SETA International VN"
        dest: "/var/www/html/index.html"

    - name: Start Nginx service
      service:
        name: nginx
        state: started
      when: "'{{ inventory_hostname }}' in groups['webservers']"

  handlers:
    - name: Restart Nginx service
      service:
        name: nginx
        state: restarted
