---
- name: Deploy Web Application with Nginx on Frontend
  hosts: webservers  # Assuming you have a group named 'webservers'
  vars:
    port: 8080

  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Setup Frontend with registration form (when applicable)
      when: inventory_hostname in groups['webservers']
      tasks:
        - name: Copy frontend files and registration form
          copy:
            src: frontend/  # Assuming both files are in the same directory
            dest: /var/www/html/
          notify: restart nginx

    - name: Create directory for web content (if needed)
      file:
        path: "/var/www/html"
        state: directory

    - name: Configure Nginx with template
      template:
        src: "nginx.conf.j2"
        dest: "/etc/nginx/sites-enabled/web"
      notify: restart nginx

    - name: Create a custom index page (optional)
      copy:
        content: "<html><body>Your web application is here!</body></html>"  # Example content
        dest: "/var/www/html/index.html"
      when: not inventory_hostname in groups['webservers']  # Optional, create only for non-webservers

    - name: Start Nginx service
      service:
        name: nginx
        state: started

  handlers:
    - name: Restart Nginx service
      service:
        name: nginx
        state: restarted
